remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Bridge Buttons
description: Free tier Tor bridges using AWS!
show_downloads: true
github:
  zip_url: https://github.com/kevinl95/BridgeButtons/archive/refs/tags/1.0.zip
  tar_url: https://github.com/kevinl95/BridgeButtons/archive/refs/tags/1.0.tar.gz